name: "[Test] Extract Issue Contents"

permissions:
  issues: write
  
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test-issue-comment:
    name: Show Issue Information
    runs-on: ubuntu-latest
    env:
      EXCLUDED_ACTOR: github-actions[bot] # Define the excluded actor in the env section
    steps:
      - name: Check actor
        run: echo "Triggered by ${{ github.actor }}, excluding $EXCLUDED_ACTOR"
        
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set issue number for issues and issue_comment events
        if: ${{ github.event_name == 'issues' || github.event_name == 'issue_comment' }}
        run: |
          echo "ISSUE_NUMBER:${{ github.event.issue.number }}"
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
      
      - name: Set issue number for workflow_dispatch event
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "ISSUE_NUMBER:${{ github.event.inputs.issueNumber }}"
          echo "ISSUE_NUMBER=${{ github.event.inputs.issueNumber }}" >> $GITHUB_ENV
        
      - name: Extract Issue Information
        id: extract_issue_info
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.issue.body }}"
          elif [ "${{ github.event_name }}" == "issue_comment" ]; then
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.comment.body }}"
          fi
          TITLE=$(echo -e $TITLE | sed ':a;N;$!ba;s/\n/%0A/g')
          BODY=$(echo -e $BODY | sed ':a;N;$!ba;s/\n/%0A/g')
          
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "${BODY}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          ISSUE_CONTENT="Title:${TITLE}\nBody:${Body}"
          echo "ISSUE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "${ISSUE_CONTENT}" >> $GITHUB_ENV
          echo "ISSUE_CONTENT" >> $GITHUB_ENV

      - name: Print Issue Information
        run: |
          echo "Title: ${{ env.TITLE }}"
          echo "Body: ${{ env.BODY }}"
          echo "Issue: ${{ env.ISSUE_CONTENT }}"
